"""core schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-05 18:40:42.076000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocations',
    sa.Column('branch', sa.String(length=32), nullable=False),
    sa.Column('share', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('branch', name=op.f('pk_allocations'))
    )
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('ref', sa.String(length=256), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates')),
    sa.UniqueConstraint('fingerprint', name=op.f('uq_candidates_fingerprint'))
    )
    op.create_table('collections_tracked',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('creator', sa.String(length=128), nullable=True),
    sa.Column('stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tracked_since', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections_tracked')),
    sa.UniqueConstraint('chain', 'market', 'slug', name=op.f('uq_collections_tracked_chain'))
    )
    op.create_table('creators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('score', sa.Numeric(precision=30, scale=12), nullable=True),
    sa.Column('stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creators')),
    sa.UniqueConstraint('chain', 'address', name=op.f('uq_creators_chain'))
    )
    op.create_table('feeds',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('quota_limit', sa.Integer(), nullable=True),
    sa.Column('quota_period', sa.String(length=16), nullable=True),
    sa.Column('quota_used', sa.Integer(), nullable=False),
    sa.Column('health', sa.String(length=32), nullable=False),
    sa.Column('health_detail', sa.Text(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_month', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('fallback_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['fallback_id'], ['feeds.id'], name=op.f('fk_feeds_fallback_id_feeds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feeds'))
    )
    op.create_table('mints_upcoming',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('collection', sa.String(length=128), nullable=False),
    sa.Column('creator', sa.String(length=128), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.Numeric(precision=30, scale=12), nullable=True),
    sa.Column('supply', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mints_upcoming')),
    sa.UniqueConstraint('chain', 'market', 'collection', name=op.f('uq_mints_upcoming_chain'))
    )
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox'))
    )
    op.create_table('signals_public',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=128), nullable=False),
    sa.Column('message_ref', sa.String(length=128), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('instrument', sa.String(length=64), nullable=True),
    sa.Column('side', sa.String(length=16), nullable=True),
    sa.Column('price_ref', sa.Numeric(precision=30, scale=12), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals_public')),
    sa.UniqueConstraint('channel', 'message_ref', name=op.f('uq_signals_public_channel'))
    )
    op.create_table('strategies',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('branch', sa.String(length=32), nullable=False),
    sa.Column('venue', sa.String(length=64), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.String(length=256), nullable=True),
    sa.Column('instruments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=True),
    sa.Column('rung', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('can_backtest', sa.Boolean(), nullable=False),
    sa.Column('stop_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies')),
    sa.UniqueConstraint('fingerprint', name=op.f('uq_strategies_fingerprint'))
    )
    op.create_index('ix_strategies_branch_status', 'strategies', ['branch', 'status'], unique=False)
    op.create_table('wallets_tracked',
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_recalc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('address', 'chain', name=op.f('pk_wallets_tracked'))
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('window_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_hash', sa.String(length=64), nullable=False),
    sa.Column('code_version', sa.String(length=64), nullable=False),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('threshold_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_measurements_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_measurements'))
    )
    op.create_table('rung_transitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.String(length=128), nullable=False),
    sa.Column('from', sa.String(length=32), nullable=False),
    sa.Column('to', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('metrics_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('by', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_rung_transitions_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rung_transitions'))
    )
    op.create_table('signals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('strategy_id', sa.String(length=128), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('instrument', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=32), nullable=False),
    sa.Column('size', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('price_ref', sa.Numeric(precision=30, scale=12), nullable=True),
    sa.Column('inputs_hash', sa.String(length=64), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('outcome_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_signals_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    op.create_index('ix_signals_strategy_decided', 'signals', ['strategy_id', 'decided_at'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('venue', sa.String(length=64), nullable=False),
    sa.Column('client_order_id', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('instrument', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=32), nullable=False),
    sa.Column('order_type', sa.String(length=32), nullable=False),
    sa.Column('qty', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('price', sa.Numeric(precision=30, scale=12), nullable=True),
    sa.Column('filled_qty', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('leverage', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('reduce_only', sa.Boolean(), nullable=False),
    sa.Column('risk_verdict', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_orders_signal_id_signals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('venue', 'client_order_id', name=op.f('uq_orders_venue'))
    )
    op.create_table('fills',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('qty', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('fee', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('fee_asset', sa.String(length=16), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_fills_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fills'))
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.String(length=128), nullable=False),
    sa.Column('open_fill', sa.String(length=64), nullable=False),
    sa.Column('close_fill', sa.String(length=64), nullable=True),
    sa.Column('pnl_gross', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('fee', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('slippage', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('funding', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('gas', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('priority_fee', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('royalty', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('pnl_net', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['close_fill'], ['fills.id'], name=op.f('fk_trades_close_fill_fills')),
    sa.ForeignKeyConstraint(['open_fill'], ['fills.id'], name=op.f('fk_trades_open_fill_fills')),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_trades_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('fills')
    op.drop_table('orders')
    op.drop_index('ix_signals_strategy_decided', table_name='signals')
    op.drop_table('signals')
    op.drop_table('rung_transitions')
    op.drop_table('measurements')
    op.drop_table('wallets_tracked')
    op.drop_index('ix_strategies_branch_status', table_name='strategies')
    op.drop_table('strategies')
    op.drop_table('signals_public')
    op.drop_table('outbox')
    op.drop_table('mints_upcoming')
    op.drop_table('feeds')
    op.drop_table('creators')
    op.drop_table('collections_tracked')
    op.drop_table('candidates')
    op.drop_table('allocations')
    # ### end Alembic commands ###
